### PR TITLE
implement magic missile spell, with simple visual effect

### PR DESCRIPTION
**Pull request by AmosHolland**
Implemented the mechanics for the magic missile spell:
- Use a raycast to detect what is being aimed at
- if it's the boss, deal damage to it
- spawn a "beam" to represent the spell that is later removed

This is blocked by a couple other PRs which is why this is a draft, just wanted to record that this is done, and begin the review process.

### CODE REVIEW

**Review by OwenBoisse — CHANGES_REQUESTED** [review]
need to improve aiming, currently doesnt always shoot where laser is pointing

**Comment by AmosHolland** [comment]
I'm not a huge fan of including the changes to aiming in the same PR as this spell but I guess we're here now so what can we do, plx review.

**Comment by OwenBoisse** [comment]
> I'm not a huge fan of including the changes to aiming in the same PR as this spell but I guess we're here now so what can we do, plx review.
> 

True but at the same time this is the only spell that has aiming

**Review by OwenBoisse — APPROVED** [review]
fixed aiming, and tested

**Review by rosefromthedead — APPROVED** [review]
This is so cool

**Comment by rosefromthedead** [comment]
I'm gonna bypass the blasted branch protection because I cleaned up the diff a little and now it thinks I'm a narcissist

**Pull request merged**
