### PR TITLE
Mesh culling real

### PR DESCRIPTION
**Pull request by rosefromthedead**

### CODE REVIEW

**Comment by rosefromthedead** [comment]
fixed and tested :+1:

**Comment by Foxinatel** [comment]
Changes have been made to make this compatible with scene mesh sharing, tested with me and Amos, and everything seems to be working correctly.

**Review by Foxinatel — APPROVED** [review]
Tested and everything works, we're good to land this.

**Review by AmosHolland — APPROVED** [review]
Looks sensible to me. Algorithm makes sense etc.

**Pull request merged**
